### ISSUE TITLE
[rosrun] Couldn't find executable

### ISSUE THREAD

**Issue by surabhi96** [surabhi96/Library-navigating-robot#19]
i got this(`[rosrun] Couldn't find executable named make_library.py below /opt/ros/indigo/share/rosserial_client`) error while trying to generate custom message for Arduino from the command:
`rosrun rosserial_client make_library.py ~/sketchbook/library adc_voltage`

**Comment by surabhi96** [comment]
Check out
https://github.com/ros-drivers/rosserial/issues/220
https://github.com/ros-drivers/rosserial/issues/96

**Comment by surabhi96** [comment]
The issue is clear enough:
`[Errno 17] File exists: '/home/surabhi/sketchbook/libraries/ros_lib'`
You have to remove the existing ros_lib folder in the path mentioned in the command 
`rosrun rosserial_client make_library.py <path to library folder where ros_lib is present> adc_voltage`
In my case, the path was `~/Arduino/libraries/` so I just removed ros_lib from there.

**Comment by surabhi96** [comment]
entered the following two commands
`rosrun rosserial_client make_libraries`
`rosrun rosserial_arduino make_libraries.py`
and it says

```
This generic make_libraries generates the non-platform specific part of a
rosserial client library, including messages. It assumes the target platform
has native float64 support, and is therefore unsuitable for use with AVR.
To generate messages for AVR, use the make_libraries script in
rosserial_arduino.

This script also does not provide the ros.h file or other hardware
abstraction. This will need to be supplied by the user.

rosrun rosserial_client make_libraries <output_path>

```

and

```
make_libraries.py generates the Arduino rosserial library files. It
requires the location of your Arduino sketchbook/libraries folder.

rosrun rosserial_arduino make_libraries.py <output_path>

```

So I enter the following command
`rosrun rosserial_arduino make_libraries.py ~/sketchbook/libraries/ adc_voltage`
to create the required headers for Arduino and add them to the "ros_lib" folder under sketchbook/libraries folder.

but I get the following
`Traceback (most recent call last): File "/opt/ros/indigo/share/rosserial_arduino/make_libraries.py", line 87, in <module> shutil.copytree(rosserial_arduino_dir+"/src/ros_lib", path+"/ros_lib") File "/usr/lib/python2.7/shutil.py", line 177, in copytree os.makedirs(dst) File "/usr/lib/python2.7/os.py", line 157, in makedirs mkdir(name, mode) OSError: [Errno 17] File exists: '/home/surabhi/sketchbook/libraries/ros_lib'`

**Comment by surabhi96** [comment]
The issue is clear enough:
`[Errno 17] File exists: '/home/surabhi/sketchbook/libraries/ros_lib'`
You have to remove the existing ros_lib folder in the path mentioned in the command
`rosrun rosserial_client make_library.py <path to library folder where ros_lib is present> adc_voltage`
In my case, the path was `~/Arduino/libraries/` so I just removed ros_lib from there.
